FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"YXBpVmVyc2lvbjogc2VydmljZWNhdGFsb2cuazhzLmlvL3YxYWxwaGExCmJpbmRhYmxlOiBGYWxz\
ZQpraW5kOiBTZXJ2aWNlQ2xhc3MKYnJva2VyTmFtZTogYW5zaWJsZS1zZXJ2aWNlLWJyb2tlcgpk\
ZXNjcmlwdGlvbjogbXktbWVtY2FjaGVkLWFwYiBkZXNjcmlwdGlvbgppZDogOTBhODgzM2EtNzJm\
Ny00MjU5LTk5YmQtNjI2ODU3MTJjNzRiCmltYWdlOiBkb2NrZXIuaW8vcGhyYWNlay9teS1tZW1j\
YWNoZWQtYXBiCmFzeW5jOiBvcHRpb25hbApleHRlcm5hbElEOiA1YzYwY2M3MTQzNGJiMGY5ZGMK\
ZXh0ZXJuYWxNZXRhZGF0YToKICBkZXBlbmRlbmNpZXM6IFsnZG9ja2VyLmlvL3BocmFjZWsvbXkt\
bWVtY2FjaGVkLWFwYjpsYXRlc3QnXQogIGRpc3BsYXlOYW1lOiBNZW1jYWNoZWQgKEFQQikKICBk\
b2N1bWVudGF0aW9uVXJsOiBodHRwczovL2dpdGh1Yi5jb20vY29udGFpbmVyLWltYWdlcy9tZW1j\
YWNoZWQKICBsb25nRGVzY3JpcHRpb246IE1lbWNhY2hlZCBhcGIgaW1wbGVtZW50YXRpb24KbWV0\
YWRhdGE6IAogIG5hbWU6IG15LW1lbWNhY2hlZC1hcGIKICBkaXNwbGF5TmFtZTogTWVtY2FjaGVk\
IChBUEIpCiAgbG9uZ0Rlc2NyaXB0aW9uOiBBbiBhcGIgdGhhdCBkZXBsYXlzIG1lbWNhY2hlZApw\
bGFuczoKLSBkZXNjcmlwdGlvbjogTWVtY2FjaGVkIGFwYiBpbXBsZW1lbnRhdGlvbgogIGV4dGVy\
bmFsSUQ6IGRlZmF1bHQKICBmcmVlOiB0cnVlCiAgbmFtZTogZGVmYXVsdAogIHBhcmFtZXRlcnM6\
IFtdCg=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chown -R apb /opt/{ansible,apb} \
    && chmod -R g=u /opt/{ansible,apb}
USER apb
